const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';

const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';

const NEW_REQUEST = 'NEW_REQUEST';
const NEW_MESSAGE = "NEW_MESSAGE";

const TYPING_START ='TYPING_START';
const TYPING_STOP = "TYPING_STOP";

const CHAT_JOINED ='CHAT_JOINED';
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USER="ONLINE_USER"

export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    TYPING_START,
    TYPING_STOP,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USER
}